version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "ğŸ” enhancement"
      - "ğŸ¤– github actions"
      - "dependencies"
    commit-message:
      prefix: â¬†
  # Python
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      - "ğŸ” enhancement"
      - "ğŸ python"
      - "dependencies"
    commit-message:
      prefix: â¬†
